title: 'Love, Passion, Travel'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2340426
  brandStrength: 0.07234043
  lightness: 1
  brandColors:
    - '#FFFFFF'
    - '#393939'
    - '#C6C6C5'
    - '#080302'
    - '#866619'
  rhythmicContrast: 0.1255319
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: 'Radeeda '
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.206383
layout_spectrum: 1
