name: 'Radeeda '
favicon: null
layout_spectrum: 0.9638298
typography_spectrum: 0.1595745
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: 'Love, Passion, Travel'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#28281F'
    - '#A4C5F0'
    - '#D6AC78'
    - '#776554'
    - '#772126'
  brandStrength: 0.0625
  lightness: 0.9375
  saturation: 0
  rhythmicContrast: 1
purpose: []
