analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.99872
title: 'Love, Passion, Travel'
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0
  brandStrength: 0.0625
  rhythmicContrast: 1
  brandColors:
    - '#28281F'
    - '#A4C5F0'
    - '#D6AC78'
    - '#776554'
    - '#772126'
  lightness: 0.9375
purpose: []
favicon: null
name: 'Radeeda '
typography_spectrum: 0.1595745
