name: 'Radeeda '
analytics: {}
purpose: []
github: true
description: just as above
cta:
  bucket: null
  version: null
  domain: null
author: {}
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content: []
layout_spectrum: 0.09787234
color:
  lightness: 0
  brandColors:
    - '#FFFFFF'
    - '#393939'
    - '#C6C6C5'
    - '#080302'
    - '#866619'
  saturation: 1
  brandStrength: 0
  rhythmicContrast: 0
content_rating:
  adult: false
typography_spectrum: 0
opengraph: {}
title: 'Love, Passion, Travel'
